### PR TITLE
Fix validation

### LINKED ISSUE #131: result box needs to be wrapped
image

### PR DESCRIPTION
**Pull request by VedJoshi**
- Fixes #131
- Wrap the result box - damn leceh pls dont break
- Add validation to assign - cannot reassing to own wedding cuz that changes the hashcode

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AssignCommand.java [hunk 1]
```diff
@@ -98,6 +100,19 @@ public CommandResult execute(Model model) throws CommandException {
...
+                Wedding wedding = weddings.get(index.getZeroBased());
+                // Check if person is client of the wedding
+                if (personToAssign.getOwnWedding() != null && personToAssign.getOwnWedding().isSameWedding(wedding)) {
+                    throw new CommandException(MESSAGE_CLIENT_ASSIGN_ERROR);
+                }
+                // Check if person is already assigned to the wedding
+                if (personToAssign.isAssignedToWedding(wedding)) {
+                    throw new CommandException(MESSAGE_DUPLICATE_WEDDING);
+                }
+            }
```
Comment (yikjunxian) [inline src/main/java/seedu/address/logic/commands/AssignCommand.java:115]: Nice handling of case when person who is a client is assigned a role

File: src/main/java/seedu/address/logic/commands/AssignCommand.java [hunk 2]
```diff
@@ -200,16 +193,42 @@ private static Person createPersonWithRole(Person personToAddRole,
...
+        }
+
+        for (Index index : weddingIndices) {
+            if (index.getZeroBased() >= lastShownList.size()) {
+                throw new CommandException(String.format(Messages.MESSAGE_INVALID_WEDDING_DISPLAYED_INDEX,
+                        lastShownList.size()));
+            }
+        }
+    }
+
```
Comment (yikjunxian) [inline src/main/java/seedu/address/logic/commands/AssignCommand.java:231]: nice validation check of wedding indices

**Review by yikjunxian — APPROVED** [review]
LGTM
